version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: ${SERVER_HOST}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

  nginx:
    image: reverse-proxy
    build:
        context: ./nginx
        dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - server