version: '3.8'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_fastapi_app
    ports:
      - "80:80"
    depends_on:
      - postgres