openapi: 3.0.3
info:
  title: Документация АПИ
  description: Документация АПИ для сайта и мобильного приложения
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /api/v1/getproducts:
    get:
      tags:
        - Общие
      summary: Получение всех позиций из бд
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Main'
        '500':
          description: Ошибка сервера
  /api/v1/getuserinfo:
    get:
      tags:
        - Общие
      summary: Получение информации о пользователе
      security:
        - cookieJWT: []
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/UserInfo'
        '401':
          description: Истек срок действия JWT токена
        '500':
          description: Ошибка сервера

  /api/v1/login:
    post:
      tags:
        - Авторизация
      summary: Авторизация пользователя
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestsBody'
      responses:
        '200':
          description: Успешная операция
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Login'
        '500':
          description: Ошибка сервера
  /api/v1/confirmCode:
    post:
      tags:
        - Авторизация
      summary: Подтверждение кода (который пришел на номер телефона)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmCodeRequestsBody'
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        '500':
          description: Ошибка сервера
  /api/v1/refresh:
    post:
      tags:
        - Авторизация
      summary: Обновление токена JWT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequestsBody'
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshReturn'
        '500':
          description: Ошибка сервера



components:
  securitySchemes:
    cookieJWT:
      type: SecuritySchemeType.HTTP
      in: Cookie
      name: jwt token
      bearerFormat: 'JWT'
      scheme: 'bearer'


  schemas:
    RefreshRequestsBody:
      type: object
      properties:
        refreshToken:
          type: string
          example: 'oicsudbnisdpfl.12edewf092f23f2.312jif02323e'

    LoginRequestsBody:
      type: object
      properties:
        number:
          type: string
          example: '79155188990'

    ConfirmCodeRequestsBody:
      type: object
      properties:
        code:
          type: string
          example: '3489'


    UserInfo:
      type: object
      properties:
        number:
          type: string
          example: '79993332255'
        email:
          type: string
          example: 'poskoreev@mail.ru'
        telegram:
          type: string
          example: 'ilyadischenko'
        promocodes:
          type: array
          description: 'Тут только личные промокоды, которые доступны конкретно этому пльзователю'
          example: [
            {
              promocode: 'zima2024',
              name: 'Промокод на скидку 20%',
              expires_at: '20.04'
            }
          ]
        bonuses:
          type: integer
          example: 130

    Position:
      type: object
      description: 'Все массивы имеют одинаковое количество элементов.
      Если это пицца, то она как правило имеет 3 размера, значит во всех массивах будет по 3 элемента (3 размера, 3 цены, 3 граммовки и тд..).
      В случае, когда цена и размер один (как на кофе к примеру), всё равно передается массив, но с одним элементом.'
      properties:
        id:
          type: integer
          example: 23
        title:
          type: string
          example: 'Пепперони'
        img:
          type: string
          example: 'https://yandex.cloud/adasdqwdsad'
        description:
          type: string
          example: 'Острая пепперони, сыр моцарелла...'
        articles:
          type: array
          example: [443212, 234124, 412321]
        bonuses:
          type: array
          example: [ 30, 40, 50 ]
        prices:
          type: array
          example: [390, 440, 550]
        sizes:
          type: array
          example: [25, 30, 35]
        quantity:
          type: array
          example: [200, 350, 600]
        in_stock:
          type: boolean
          example: true

    Category:
      type: object
      properties:
        type:
          type: string
          description: Типы продукта (Пиццы, Напитки, Дессерты)
          example: 'Пиццы'
        items:
          $ref: '#/components/schemas/Position'


    Main:
      type: object
      properties:
        products:
          items:
            $ref: '#/components/schemas/Category'

    Login:
      type: object
      properties:
        userdata:
          items:
            $ref: '#/components/schemas/UserInfo'
        accessToken:
          type: string
          example: 'asdfpodsfkpsdfl[sdpfl.sfiodsjfmokldsf.fdshfhbsdjvds'
        refreshToken:
          type: string
          example: 'oicsudbnisdpfl.12edewf092f23f2.312jif02323e'

    RefreshReturn:
      type: object
      properties:
        accessToken:
          type: string
          example: 'asdfpodsfkpsdfl[sdpfl.sfiodsjfmokldsf.fdshfhbsdjvds'
        refreshToken:
          type: string
          example: 'oicsudbnisdpfl.12edewf092f23f2.312jif02323e'



