"""add products and prod.categories

Revision ID: 46ca2cab839c
Revises: 
Create Date: 2024-02-02 20:40:01.072491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46ca2cab839c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userjwt')

    # op.drop_index('idx_userjwt_user_id_af14a7', table_name='userjwt')
    op.drop_table('user_promocodepercent')
    op.drop_table('user')

    op.drop_table('menu')
    op.drop_table('promocodepercent')
    op.drop_table('products')
    op.drop_table('productscategories')
    op.drop_table('aerich')
    op.drop_table('userblacklist')
    op.drop_table('product_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userjwt',
    sa.Column('refresh_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userjwt_user_id_fkey', ondelete='CASCADE')
    )
    op.create_index('idx_userjwt_user_id_af14a7', 'userjwt', ['user_id'], unique=False)
    op.create_table('product_table',
    sa.Column('uuid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='product_table_pkey')
    )
    op.create_table('userblacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='userblacklist_pkey')
    )
    op.create_table('aerich',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('app', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='aerich_pkey')
    )
    op.create_table('productscategories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('productscategories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='productscategories_pkey'),
    sa.UniqueConstraint('type', name='productscategories_type_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('img', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('promocodepercent',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('promocodepercent_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('for_all', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('discount', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('start_day', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('min_sum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='promocodepercent_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('menu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('bonuses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_view', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_have', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('categories_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categories_id'], ['productscategories.id'], name='menu_categories_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='menu_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='menu_pkey')
    )
    op.create_table('user_promocodepercent',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('promocodepercent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['promocodepercent_id'], ['promocodepercent.id'], name='user_promocodepercent_promocodepercent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_promocodepercent_user_id_fkey', ondelete='CASCADE')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('telegram', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bonuses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('number', name='user_number_key'),
    sa.UniqueConstraint('telegram', name='user_telegram_key')
    )
    # ### end Alembic commands ###
