"""add test table

Revision ID: 9976affecdae
Revises: 76c0921e5d85
Create Date: 2024-02-02 21:46:51.104168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9976affecdae'
down_revision: Union[str, None] = '76c0921e5d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'product',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'category',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu', 'product',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
